### ISSUE TITLE
jcenter shutting down

### ISSUE THREAD

**Issue by gagarin55** [zcash/kotlin-bip39#5]
Hello, 

jcenter repo is shutting down. Do you have any plans to migrate?

**Comment by gmale** [comment]
Yes. I plan to migrate to Maven Central and move old versions, in the process. I'll update that ticket when complete. I've already setup the sonatype account for zcash, just need to do the work of configuring the repos for deployment. It was very urgent until they moved the timeline back. I hope to get to it soon.

**Comment by gmale** [comment]
Version 1.0.2 is [available on maven central](https://repo1.maven.org/maven2/cash/z/ecc/android/kotlin-bip39/) and I've made the related [build configuration changes](https://github.com/zcash/kotlin-bip39/pull/6/files) and updated the [README badge](https://github.com/zcash/kotlin-bip39/commit/80e63c8d9cff43fc1bfd42185657422defe1aea6).

All future releases will publish to Maven Central.

_Note: there are no differences in 1.0.2 from 1.0.1. I just bumped the version to avoid confusion and ensure that removing JCenter worked._
